### ISSUE TITLE
加载6张以上图片的时候卡顿，前三四张时候还可以，第五第六张的时候，滑动有卡顿情况

### ISSUE THREAD

**Issue by luojialun** [MikaelZero/Diooto#23]

**Comment by moyokoo** [comment]
具体使用代码怎么编写的

**Comment by luojialun** [comment]
> 具体使用代码怎么编写的

是添加的本地依赖，这是使用glide加载图片的部分
 private void showGlidePic() {
        GlideApp.with(getContext())
                .load(url)
                .listener(new RequestListener<Drawable>() {
                    @Override
                    public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target, DataSource dataSource, boolean isFirstResource) {
                        if (null != resource) {
                            int w = resource.getIntrinsicWidth();
                            int h = resource.getIntrinsicHeight();
                            dragDiootoView.putData(
                                    contentViewOriginModel.getLeft(), contentViewOriginModel.getTop(),
                                    contentViewOriginModel.getWidth(), contentViewOriginModel.getHeight(),w, h);
                            dragDiootoView.show(true);
                        }
                        return false;
                    }
                })
                .into(sketchImageView);
    }

**Comment by luojialun** [comment]
调用部分代码 
/**
     * 动态显示多张图片
     *
     * @param context
     * @param urlLists      图片数组
     * @param smallUrlLists 封面图片数组
     * @param position      当前点击你的位置
     * @param rv            RecyclerView
     * @param headerSize    有几个头
     * @param picId         控件id，为了动态计算位置，做动画
     */
    public static void showPicsStart(final Context context, List<String> urlLists, List<String> smallUrlLists, int position, RecyclerView rv, int headerSize, int picId) {
        if (CheckClickUtils.isFastClick()) {
            return;
        }
        if (null != urlLists && null != smallUrlLists) {
            final String[] urlArrys = new String[urlLists.size()];
            urlLists.toArray(urlArrys);
            final String[] smallUrlArrys = new String[smallUrlLists.size()];
            smallUrlLists.toArray(smallUrlArrys);
            Diooto diooto = new Diooto(context)
                    .indicatorVisibility(View.VISIBLE)
                    .urls(urlArrys)
                    .type(DiootoConfig.PHOTO)
                    .immersive(true)
                    .setProgress(new ProgressBarProgress())
                    .position(position, headerSize)
                    .views(rv, picId)
                    .loadPhotoBeforeShowBigImage(new Diooto.OnLoadPhotoBeforeShowBigImageListener() {
                        @Override
                        public void loadView(final SketchImageView sketchImageView, int position) {
                            sketchImageView.displayImage(smallUrlArrys[position]);
                        }
                    })
                    .start();
        }
    }

**Comment by luojialun** [comment]
请问有遇到过类似的情况吗

**Comment by moyokoo** [comment]
showGlidePic 方法是哪里的？

**Comment by luojialun** [comment]
我在ImageFragment中找到loadImage的方法，因为公司之前用的glide加载证书加密的图片，前人先用了sketchimageview.displayImage()加载图片，然后在失败的回调中再用glide加载图片，导致了卡顿。我翻了sketch的issue，里面有提到混用会造成内存暴增，应该能解释卡顿的情况，我去除了sketchimageview.displayImage()，直接使用glide加载图片（showGlidePic），但是最后的显示结果图片的大小（宽度）不对，先sketchimageview.displayImage()再用glide的显示效果却是对的，有点迷惑，请指教

**Comment by luojialun** [comment]
或者有没有sketchimageview.displayImage()加载证书加密图片的例子，我也没找到相关的信息

**Comment by luojialun** [comment]
虽然图片加载出来了（宽度错误），但是sketchview还是有报Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by moyokoo** [comment]
如果混用会导致内存暴增 那就只能使用sketch了 因为长图效果是基于sketch的 非长图是准备后续更新再做支持

**Comment by luojialun** [comment]
那有sketchimageview加载证书加密图片的例子吗，我用glide加载sketchImageView日志中还是有证书确实的错误

**Comment by moyokoo** [comment]
这个我就没太具体研究了
