### ISSUE TITLE
有个问题，recyleview最后一张不需要大图显示，如何实现

### ISSUE THREAD

**Issue by dary123** [MikaelZero/Diooto#25]
发现如果传入的数组长度和实际recyleview包含的图片数目不一致时，点击放大会报错，没有头部布局，如何去掉尾部最后一张图片展示呢

**Comment by MikaelZero** [comment]
position的参数怎么传的

**Comment by dary123** [comment]
传的就是当前点击的图片位置

**Comment by MikaelZero** [comment]
有没有传headsize

**Comment by dary123** [comment]
传了0，因为我没有头部

**Comment by MikaelZero** [comment]
这样处理会出错么？具体什么错误

**Comment by dary123** [comment]
数组越界，我明明点击的是当前posi位置，比如有8个图片,我点击的第一张，却报当前index是8,数组长度是8，导致数组越界

**Comment by dary123** [comment]
如果我传入的图片数组长度与recyleview内部图片实际数目一致，就不会报错

**Comment by MikaelZero** [comment]
传入的图片数组长度与recyleview内部图片实际数目不是本来就需要一致么  不一致数目肯定不对啊

**Comment by MikaelZero** [comment]
你是想recyclerview有9张   大图显示只想显示8张？

**Comment by dary123** [comment]
是的，最后一张其实是加号，点击后会跳转到系统相册上传图片，这个加号图片不能用于大图展示

**Comment by MikaelZero** [comment]
传的view是recyclervew还是view数组

**Comment by dary123** [comment]
recyclervew

**Comment by dary123** [comment]
.views(rvPic, R.id.pic_url)

**Comment by dary123** [comment]
第一个参数是recyleview，第二个参数是单个图片的id

**Comment by MikaelZero** [comment]
你需要传view数组 否则他会根据recyclerview的item数量来实例化

**Comment by dary123** [comment]
谢谢大神，解决了
